### ISSUE TITLE
Feature Request: add an option for exclusive, instead of inclusive, ColorMasks

### ISSUE THREAD

**Issue by bikinavisho** [Floogen/FashionSense#12]
What I'm proposing is the inverse of ColorMasks. So where ColorMasks say "only replace this color", this option would say "replace everything EXCEPT this color". Not sure how difficult that would be to do programmatically, but it would make it very convenient for things where you want everything to change except for a small section. 

For example, if you had a hairstyle with a bow, just exclude the bow's pixel colors instead of the shaded hair pixel colors which would be a lot more work to get all the colors of.

**Comment by Floogen** [comment]
This is now possible with `ColorMaskLayers`, specifically its `IgnoreUserColorChoice` property.

See [this page](https://github.com/Floogen/FashionSense/wiki/Color-Mask-Layers-Property) for more details.

Thank you for the suggestion!
