### ISSUE TITLE
Feature Request: Create Public Interface for Setting Appearance Model

### ISSUE THREAD

**Issue by bikinavisho** [Floogen/FashionSense#13]
It would be nice if other modders could hook into Fashion Sense to programmatically 

- equip a Fashion Sense hairstyle
- equip a Fashion Sense hat
- equip a Fashion Sense accessory (in slot 1, 2, or 3)
- equip a Fashion Sense shirt
- equip a Fashion Sense pants
- equip a Fashion Sense boots
- equip a Fashion Sense sleeves 

using the method outlined here: https://stardewvalleywiki.com/Modding:Modder_Guide/APIs/Integrations

**Comment by Floogen** [comment]
See v4.5.0 for the implementation of the API.

Documentation can be [found on the wiki](https://github.com/Floogen/FashionSense/wiki/Fashion-Sense-API).
