### ISSUE TITLE
When wearing pants with HideWhileSwimming true, character is naked while swimming 

### ISSUE THREAD

**Issue by bikinavisho** [Floogen/FashionSense#14]
As the title says, when wearing pants that have `HideWhileSwimming` set to true, the character is naked while swimming. Instead of requiring all content pack creators who make pants add on a swimsuit texture to each pants, I was thinking the framework could use a default swimsuit texture if the Farmer is wearing pants with `HideWhileSwimming` set to true. 

A bigger change would be to implement a Swimsuit model that activates while a character goes swimming, but I feel like the above suggestion is simple and clean and doesn't have any implications of things like a mod that adds a mermaid tail which is intentionally not hidden while swimming. 

Small note: I noticed through testing that this only happens when a character has pants with `HideWhileSwimming` true from Fashion Sense equipped. It is not tied to having shirts with `HideWhileSwimming` true from Fashion Sense equipped. When you have FS shirt equipped and vanilla pants, your character will change into the default vanilla swimsuit. When  you have FS pants equipped and vanilla shirt, your character is naked. When you have FS pants and FS shirt equipped, your character is naked. I have surmised from this data that the swimsuit texture is tied to the pants, not the shirt.

**Comment by Floogen** [comment]
I'm unable to replicate this behavior when using the [Pink Grass Skirt](https://github.com/Floogen/FashionSense/tree/development/FashionSense/Examples/%5BFS%5D%20Example%20Pack/Pants/PinkGrassSkirt) (found in the example pack) while using the game's bathhouse.

`HideWhileSwimming` and `HideWhileWearingBathingSuit` are by default `true` and should automatically display the farmer's swimsuit sprites.

To help further, I'll need a SMAPI log and the `pants.json` file that you're seeing this behavior on.

**Comment by bikinavisho** [comment]
I figured it out: it happens when I have a Get Glam shoe equipped with a Fashion Sense pants. 

I'm going to go ahead and close this since Get Glam is kind of dying/dead so coding something special for compatibility probably isn't worth your time.
