### ISSUE TITLE
File empty

### ISSUE THREAD

**Issue by NILLIUN** [Floogen/FashionSense#6]
![ScreenShot_20211201001854](https://user-images.githubusercontent.com/95378052/144297686-9758f192-4aad-479e-b8c3-6e730b73e264.jpeg)

![ScreenShot_20211201154625](https://user-images.githubusercontent.com/95378052/144303949-aa536405-1d2e-4893-b6f2-41355d02d4f2.jpeg)

I loved the practicality of the mod for clothes and others, I would love to use it someday :) but I had some problems with it, first I downloaded version 3.0.0, this error appeared in smapi:.

![ScreenShot_20211201164036](https://user-images.githubusercontent.com/95378052/144303565-d7fbca2c-12d2-48da-b9ab-fdf3f33bada9.jpeg)

Soon after I decided to download the previous version 2.7.1, I managed to take the items to the game, although when I press the mirror, the mirror says that the "PK" file (My folder where I keep the contents) is empty, despite having.
#

**Comment by Floogen** [comment]
I need a log file to help, though I appreciate the other details you put together. Without a log, it is hard to properly determine the issue.

[See here for instructions on how to upload a log](https://smapi.io/log).

**Comment by NILLIUN** [comment]
https://smapi.io/log/83ae9318a9ad4c209c90d4b0a6036b1a
Here it is!

**Comment by Floogen** [comment]
There are a couple issues here.

Firstly, Fashion Sense v3.0.0 requires SDV 1.5.5, _per the download description on Nexus_. You're currently using SDV 1.5.4, hence the errors you are seeing.

Secondly, it would seem that you may be using a pirated copy of Stardew Valley, which I don't offer support for.

**Comment by NILLIUN** [comment]
Thanks for the answer, I understand, I'm afraid I can't use it then, but keep doing a good job you guys, it's an amazing mod.

**Comment by Floogen** [comment]
Thank you for the kind words! Whenever you do get a legitimate copy, I'll be more than happy to help with any further issues you have.
